name: Autofix

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.repository == 'rust-lang/glacier'

    env:
      RUST_LIB_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "rustbot"
          git config --global user.email "rustbot@users.noreply.github.com"

      - name: Build
        uses: ./.github/actions/build

      - run: ./target/release/autofix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
