name: Autofix

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'rust-lang/glacier'

    env:
      RUST_LIB_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "rustbot"
          git config --global user.email "rustbot@users.noreply.github.com"

      - name: Configure rustup
        run: |
          rustup set profile minimal
          rustup toolchain install nightly
          rustup target add x86_64-pc-windows-msvc

      - run: cargo run -p autofix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
